name: Note App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: all-steps
    runs-on: ubuntu-latest
    env:
      NOTE_GROUP: shahin-nazarov
      NOTE_APP_NAME: note
      NOTE_APP_VERSION: 0.0.1
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host
    - name: Build and push to local registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: localhost:5000/${{ env.NOTE_GROUP }}/${{ env.NOTE_APP_NAME }}:${{ env.NOTE_APP_VERSION }}
        build-args: |
          NOTE_APP_NAME=${{ env.NOTE_APP_NAME }}
          NOTE_APP_VERSION=${{ env.NOTE_APP_VERSION }}

